# Generated by Django 2.1.5 on 2019-01-23 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190123_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='introduction',
            field=models.TextField(blank=True, verbose_name='自我介紹'),
        ),
    ]
